package constants;

public enum Attribute {
    TEXT, CLASS, ID, HREF, STYLE, TITLE, DIR, LANG, ACCESSKEY, TABINDEX, VALUE,
    ONCLICK, ONDBLCLCICK, ONMOUSEDOWN, ONMOUSEMOVE, ONMOUSEOUT, ONMOUSEOVER, ONMOUSEUP, ONKEYDOWN, ONKEYPRESS,
    ONKEYUP, ONBLUR, ONCHANGE, ONSELECT, CODE, OBJECT, NOHREF, ALINK, BACKGROUND, LINK, VLINK,
    ACTION, ENCTYPE, METHOD, NORESIZE, PROFILE, NOSHADE, XMLNS, ISMAP, CHECKED, MAXLENGTH,
    FOR, CONTENT, SCHEME, CLASSID, CODETAG, DATA, DECLARE, STANDBY, START, SELECTED, VALUETYPE, DEFER,
    MULTIPLE, CELLPADDING, FRAME, RULES, SUMMARY, HEADERS, ALT, BGCOLOR, BORDER, CHAR, CHAROFF, CHARSET, CITE, COMPACT, DISABLED, HEIGHT,
    HSPACE, LONGDESC, NAME, SIZE, SRC, TARGET, TYPE, VALIGN, VSPACE, WIDTH,
    COORDS, SHAPE, HREFLANG, REL, REV, ARCHIVE, CODEBASE, COLOR, FACE, SPAN, DATETIME,
    ACCEPT, FRAMEBORDER, MARGINHEIGHT, SCROLLING, MARGINWIDTH, COLS, ROWS, USEMAP,
    READONLY, MEDIA, LABEL, ABBR, AXIS, COLSPAN, NOWRAP, ROWSPAN, SCOPE
}